FROM postgres:14.1

# RUN groupadd -g 60005 ccmmma
# RUN useradd -u 60005 -g 60005 ccmmma

RUN usermod -u 60005 postgres
RUN groupmod -g 60005 postgres

RUN apt-get update && apt-get install -y postgresql-14-postgis-3

COPY FUMI2.sql /docker-entrypoint-initdb.d/FUMI2.sql

# RUN chown -R ccmmma:ccmmma /var/lib/postgresql/data/
# CMD ["/usr/local/bin/docker-entrypoint.sh","postgres"]

CMD ["postgres"]


