version: '3'

services:
  app:
    container_name: container_FUMI2
    build:
      dockerfile: Dockerfile-fumi2
    ports:
      - "8085:80"
    volumes:
      - /storage/ccmmma/prometeo/data/opendap/apps/smoketracer:/home/fumi2/FUMI2/static/smoketracer
    depends_on:
      - db
    networks:
      - net_FUMI2
  
  db:
    container_name: container_postgres_FUMI2
    build: 
      dockerfile: Dockerfile-postgres
    volumes:
      - ./postgresql_data4:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    restart: always
    networks:
      - net_FUMI2

networks:
  net_FUMI2:
    driver: bridge