FROM python:3.9.11
# FROM python:latest
# FROM ubuntu:latest

# only for test .
#RUN groupadd -g 3001 ccmmma
#RUN groupadd -g 3050 fumi2
#RUN useradd -u 3050 -g 3050 -G 3001 -m -s /bin/bash fumi2 && echo 'root:ciao' | chpasswd

RUN groupadd -g 60005 ccmmma
RUN groupadd -g 60050 fumi2 
RUN useradd -u 60050 -g 60050 -G 60005 -m -s /bin/bash fumi2 

COPY . /home/fumi2/FUMI2
WORKDIR /home/fumi2/FUMI2

RUN mkdir /home/fumi2/.ssh/
RUN mv id_rsa /home/fumi2/.ssh/
RUN chmod 400 /home/fumi2/.ssh/id_rsa
RUN mv id_rsa.pub /home/fumi2/.ssh/
RUN chmod 644 /home/fumi2/.ssh/id_rsa.pub

# RUN mv known_hosts /home/fumi2/.ssh/
# RUN chmod 644 /home/fumi2/.ssh/known_hosts
# RUN mv .ssh /home/fumi2
# RUN mv .ssh/id_dsa /home/fumi2/.ssh/
# RUN chown fumi2:fumi2 /home/fumi2/.ssh/id_dsa
# RUN chmod 400 /home/fumi2/.ssh/id_dsa

RUN apt-get update && apt-get install -y expect && apt-get install -y vim
RUN pip3 install -r requirements.txt
RUN chmod o+x RequestManager.py
RUN chown -R fumi2:fumi2 /home/fumi2

USER fumi2 

ENTRYPOINT [ "python3", "/home/fumi2/FUMI2/RequestManager.py"]



