version: '3'

services:
  app:
    container_name: container_FUMI2
    build:
      dockerfile: Dockerfile-fumi2
    ports:
      - "8085:80"
    volumes:
      - /storage/ccmmma/prometeo/data/opendap/apps/smoketracer:/home/fumi2/FUMI2/static/smoketracer
    #  - /storage/ccmmma/prometeo/data/opendap/pippo/smoketracer:/home/fumi2/FUMI2/static/smoketracer
    # -  /home/d.caramiello/FUMI2/src/root:/home/fumi2/FUMI2/dati_prova
    depends_on:
      - db
    #  - db_mongo
    networks:
      - net_FUMI2
  
  db:
    container_name: container_postgres_FUMI2
    build: 
      dockerfile: Dockerfile-postgres
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db
    #volumes:
    #  - /home/d.caramiello/SmokeTracer/FUMI2.sql:/docker-entrypoint-initdb.d/FUMI2.sql
    restart: always
    networks:
      - net_FUMI2
  
  # L'idea è usare mongo db per fare resotre dei places e utilizzare quei dati per creare una collezione places per postgresql.
  # All'avvio del container , manualmente :
  #
  # 1) entrare nel container di fumi2 e lanciare lo script python 'inizialize_spatial_queries_dbs.py'
  # 2) uscire dal container e killare il container di mongo db 
  
  #db_mongo:
  #  container_name: container_mongodb_FUMI2
  #  build:
  #    dockerfile: Dockerfile-mongodb
  #  restart: always
  #  networks:
  #    - net_FUMI2
  #  depends_on:
  #    - db 
  

networks:
  net_FUMI2:
    driver: bridge
